version: '3'

services:
  nextcloud:
    build: ./nextcloud
    environment:
      - TZ=$TZ
      - MYSQL_HOST=db:3306
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    env_file:
      - "./env_files/nextcloud.env"
      - "./env_files/db.env"
    volumes:
      - "./data/nextcloud:/var/www/html"
    depends_on:
      - db
    restart: always
    ports:
      - "${NEXTCLOUD_PORT}:80"
    networks:
      - nextcloud_net
  db:
    build: ./db
    environment:
      - TZ=$TZ
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    env_file:
      - "./env_files/db.env"
    volumes:
      - "./data/db:/var/lib/mysql"
    restart: always
    ports:
      - "8888:3306"
    networks:
      - nextcloud_net
  sync:
    build: ./sync
    environment:
      - TZ=$TZ
    env_file:
      - "./env_files/nextcloud.env"
    volumes:
      - "./data/sync/config:/usr/src/sync/config/default"
      - "./data/sync/logs:/var/log/rclone-sync"
      - "./data/nextcloud/data/$SYNC_CONFIG_DIR:/usr/src/sync/config/from-nextcloud:ro"
    restart: always
    networks:
      - nextcloud_net

networks:
  nextcloud_net:
    driver: bridge

